apiVersion: v1
appVersion: "1.0"
description: A service publishing a model catalogue in a standardized format
name: model-publisher
version: 0.1.0
home: https://github.com/Informasjonsforvaltning/model-publisher