apiVersion: v1
appVersion: "1.0"
description: A service that transforms our harvested data to make them more suited for doing analytics
name: fdk-data-transformation-harvester
version: 0.1.0
home: https://github.com/Informasjonsforvaltning/fdk-data-transformation-harvester