#DValues for staging environment
NAMESPACE: prod

FDK_HARVEST_SCHEDULER_RABBIT_HOST: rabbitmq
FDK_HARVEST_SCHEDULER_RABBIT_PORT: 5672
FDK_HARVEST_SCHEDULER_RABBIT_USER: changeme
FDK_HARVEST_SCHEDULER_RABBIT_PASS: changeme