apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  annotations:
    cloud.google.com/backend-config: '{"default": "fdk-cms-backend"}'
  labels:
    fdk.service: fdk-cms-admin-service
  name: fdk-cms-admin-service
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  type: NodePort
  ports:
    - name: "1337"
      port: 1337
      targetPort: 1337
    - name: "8080"
      port: 8080
      targetPort: 1337
  selector:
    fdk.service: fdk-cms-admin-service
status:
  loadBalancer: {}
