apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  creationTimestamp: null
  labels:
    fdk.service: fdk-cms-backend
  name: fdk-cms-backend
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  iap:
    enabled: true
    oauthclientCredentials:
      secretName: {{ required "Missing value FDK_CMS_SERVICE_IAP_SECRETNAME" .Values.FDK_CMS_SERVICE_IAP_SECRETNAME }}
status: {}
