apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    fdk.service: reference-data
  name: reference-data
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        fdk.service: reference-data
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            secretKeyRef:
              name: common-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: SPRING_PROFILES_ACTIVE
        - name: themesHttpUsername
          valueFrom:
            secretKeyRef:
              name: fdk-reference-data-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: FDK_REFERENCE_DATA_THEMESHTTPUSERNAME
        - name: themesHttpPassword
          valueFrom:
            secretKeyRef:
              name: fdk-reference-data-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: FDK_REFERENCE_DATA_THEMESHTTPPASSWORD
        name: reference-data
        image: {{ required "Missing value DOCKER_IMAGE_NAME" .Values.DOCKER_IMAGE_NAME }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: {{ required "Missing value FDK_REFERENCE_DATA_MEMORY" .Values.FDK_REFERENCE_DATA_MEMORY | quote }}
        volumeMounts:
        - mountPath: /tdb
          name: reference-data-claim0
      restartPolicy: Always
      volumes:
      - name: reference-data-claim0
        persistentVolumeClaim:
          claimName: reference-data-claim0
status: {}