apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    fdk.service: reference-data
  name: reference-data
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  replicas: 1
  selector:
    matchLabels:
      fdk.service: reference-data
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        fdk.service: reference-data
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/reference-data/actuator/prometheus"
    spec:
      containers:
      - env:
        - name: MONGODB_USERNAME
          valueFrom:
            secretKeyRef:
              name: reference-data-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: MONGODB_USER
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: reference-data-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: MONGODB_PASSWORD
        - name: MONGODB_DATABASE
          valueFrom:
            secretKeyRef:
              name: reference-data-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: MONGODB_DATABASE
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: reference-data-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: API_KEY
        - name: MONGODB_AUTH_DATABASE
          valueFrom:
            secretKeyRef:
              name: mongo-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: MONGO_AUTH_DB
        - name: MONGODB_HOST
          valueFrom:
            secretKeyRef:
              name: mongo-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: MONGODB_HOST
        - name: MONGODB_PORT
          valueFrom:
            secretKeyRef:
              name: mongo-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: MONGO_PORT
        - name: CATALOG_ADMIN_SERVICE_URI
          valueFrom:
            secretKeyRef:
              name: commonurl-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: CATALOG_ADMIN_SERVICE_HOST
        name: reference-data
        image: {{ required "Missing value DOCKER_IMAGE_NAME" .Values.DOCKER_IMAGE_NAME }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: {{ required "Missing value FDK_REFERENCE_DATA_MEMORY" .Values.FDK_REFERENCE_DATA_MEMORY | quote }}
            cpu: {{ required "Missing value FDK_REFERENCE_DATA_CPU" .Values.FDK_REFERENCE_DATA_CPU | quote }}
          limits:
            memory: {{ required "Missing value FDK_REFERENCE_DATA_MEMORY" .Values.FDK_REFERENCE_DATA_MEMORY | quote }}
      restartPolicy: Always
