apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    fdk.service: fdk-reports-bff
  name: fdk-reports-bff
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  replicas: 1
  selector:
    matchLabels:
      fdk.service: fdk-reports-bff
  strategy:
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        fdk.service: fdk-reports-bff
    spec:
      containers:
      - env:
        - name: ORGANIZATION_CATALOG_URL
          valueFrom:
            secretKeyRef:
              name: commonurl-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: ORGANIZATION_CATALOGUE_HOST
        - name: CONCEPT_HARVESTER_URL
          valueFrom:
            secretKeyRef:
              name: commonurl-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: FDK_CONCEPT_HARVESTER_URI
        - name: DATASET_HARVESTER_URL
          valueFrom:
            secretKeyRef:
              name: commonurl-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: FDK_DATASET_HARVESTER_URI
        - name: DATASERVICE_HARVESTER_URL
          valueFrom:
            secretKeyRef:
              name: commonurl-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: FDK_DATASERVICE_HARVESTER_URI
        - name: INFORMATIONMODELS_HARVESTER_URL
          valueFrom:
            secretKeyRef:
              name: commonurl-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: FDK_FULLTEXT_SEARCH_BASE_URI
        - name: REFERENCE_DATA_URL
          valueFrom:
            secretKeyRef:
              name: commonurl-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: FDK_REFERENCE_DATA_BASE_URI
        - name: ELASTIC_HOST
          valueFrom:
            secretKeyRef:
              name: fdk-reports-store-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: FDK_REPORTS_STORE_HOST
        - name: ELASTIC_PORT
          valueFrom:
            secretKeyRef:
              name: fdk-reports-store-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: FDK_REPORTS_STORE_PORT
        - name: FDK_BASE
          valueFrom:
            secretKeyRef:
              name: commonurl-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: FDK_BASE_URI
        - name: SPARQL_BASE
          valueFrom:
            secretKeyRef:
              name: commonurl-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: FDK_SPARQL_API_BASE_URI
        name: fdk-reports-bff
        image: {{ required "Missing value DOCKER_IMAGE_NAME" .Values.DOCKER_IMAGE_NAME }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: {{ required "Missing value FDK_REPORTS_BFF_MEMORY" .Values.FDK_REPORTS_BFF_MEMORY | quote }}
        livenessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 150
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 5
      restartPolicy: Always
status: {}
