kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    fdk.service: static-rdf-server-claim0
  name: static-rdf-server-claim0
  annotations:
    helm.sh/resource-policy: keep
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
        storageClassName: ""
        volumeName: {{ required "Missing value STATIC_RDF_SERVER_VOLUMENAME" .Values.STATIC_RDF_SERVER_VOLUMENAME }}
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ required "Missing value STATIC_RDF_SERVER_STORAGESIZE" .Values.STATIC_RDF_SERVER_STORAGESIZE }}
{{- $pvName := required "Missing value STATIC_RDF_SERVER_VOLUMENAME" .Values.STATIC_RDF_SERVER_VOLUMENAME }}
{{- if not (lookup "v1" "PersistentVolume" "" $pvName) }}
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ $pvName }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  storageClassName: ""
  capacity:
    storage: {{ required "Missing value STATIC_RDF_SERVER_STORAGESIZE" .Values.STATIC_RDF_SERVER_STORAGESIZE }}
  accessModes:
    - ReadWriteOnce
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.kubernetes.io/zone
          operator: In
          values:
          - {{ required "Missing value GCE_ZONE" .Values.GCE_ZONE }}
  gcePersistentDisk:
    pdName: {{ $pvName }}
    fsType: ext4
{{- end }}
