kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    fdk.service: static-rdf-server-claim0
  name: static-rdf-server-claim0
  annotations:
    helm.sh/resource-policy: keep
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  storageClassName: ""
  volumeName: {{ required "Missing value STATIC_RDF_SERVER_VOLUMENAME" .Values.STATIC_RDF_SERVER_VOLUMENAME }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ required "Missing value STATIC_RDF_SERVER_STORAGESIZE" .Values.STATIC_RDF_SERVER_STORAGESIZE }}
