apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    fdk.service: fdk-dataset-preview-service
  name: fdk-dataset-preview-service
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  replicas: 1
  selector:
    matchLabels:
      fdk.service: fdk-dataset-preview-service
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        fdk.service: fdk-dataset-preview-service
    spec:
      containers:
      - env:
        - name: NAMESPACE
          valueFrom:
            secretKeyRef:
              name: common-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: NAMESPACE
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: common-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: FDK_DATASET_PREVIEW_API_KEY
        - name: ALLOWED_ORIGINS
          valueFrom:
            secretKeyRef:
              name: common-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: FDK_DATASET_PREVIEW_ALLOWED_ORIGINS
        image: {{ required "Missing value DOCKER_IMAGE_NAME" .Values.DOCKER_IMAGE_NAME }}
        imagePullPolicy: Always
        name: fdk-dataset-preview-service
        ports:
          - containerPort: 8080
        resources:
          requests:
            memory: {{ required "Missing value FDK_DATASET_PREVIEW_SERVICE_MEMORY" .Values.FDK_DATASET_PREVIEW_SERVICE_MEMORY | quote }}
            cpu: {{ required "Missing value FDK_DATASET_PREVIEW_SERVICE_CPU" .Values.FDK_DATASET_PREVIEW_SERVICE_CPU | quote }}
          limits:
            memory: {{ required "Missing value FDK_DATASET_PREVIEW_SERVICE_MEMORY" .Values.FDK_DATASET_PREVIEW_SERVICE_MEMORY | quote }}
        livenessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 150
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 5
      restartPolicy: Always
