apiVersion: v1
appVersion: "1.0"
description: FDK Fulltext Search Rabbit Consumer
name: fdk-fulltext-search-rabbit-consumer
version: 0.1.0
home: https://github.com/Informasjonsforvaltning/fdk-fulltext-search-rabbit-consumer