apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    fdk.service: fdk-dataset-harvester-gui
  name: fdk-dataset-harvester-gui
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  replicas: 1
  selector:
    matchLabels:
      fdk.service: fdk-dataset-harvester-gui
  strategy:
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        fdk.service: fdk-dataset-harvester-gui
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                secretKeyRef:
                  name: common-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
                  key: SPRING_PROFILES_ACTIVE
            - name: harvester_adminPassword
              valueFrom:
                secretKeyRef:
                  name: fdk-registration-api-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
                  key: FDK_REGISTRATION_API_HARVESTERPASSWORD
            - name: harvester_adminUsername
              valueFrom:
                secretKeyRef:
                  name: fdk-registration-api-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
                  key: FDK_REGISTRATION_API_HARVESTERUSERNAME
          image: {{ required "Missing value DOCKER_IMAGE_NAME" .Values.DOCKER_IMAGE_NAME }}
          imagePullPolicy: Always
          name: fdk-dataset-harvester-gui
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: {{ required "Missing value FDK_DATASET_HARVESTER_GUI_MEMORY" .Values.FDK_DATASET_HARVESTER_GUI_MEMORY | quote }}
          livenessProbe:
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
      restartPolicy: Always
status: {}