#DValues for staging environment
#todo: namespace bør ikke være hardkodet. Vil ha det inn i Jenkinsfile (kan settes med --set)
NAMESPACE: prod

#variabler som skal være her
MONGO_USERNAME: mongouser
MONGO_PASSWORD: mon3321pass4448wd
MONGO_HOST: tmp-mongodb:27017