apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dcat-ap-no-validator-gui
  name: dcat-ap-no-validator-gui
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dcat-ap-no-validator-gui
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dcat-ap-no-validator-gui
    spec:
      containers:
      - env:
        - name: ENV
          valueFrom:
            secretKeyRef:
              name: common-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: NAMESPACE
        - name: FDK_REGISTRATION_BASE_URI
          valueFrom:
            secretKeyRef:
              name: commonurl-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: FDK_REGISTRATION_BASE_URI
        - name: ADMIN_GUI_BASE_URI
          valueFrom:
            secretKeyRef:
              name: commonurl-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: ADMIN_GUI_BASE_URI
        - name: VALIDATOR_API_HOST
          valueFrom:
            secretKeyRef:
              name: commonurl-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: DCAT_AP_NO_VALIDATOR_SERVICE_BASE_URI
        - name: FDK_BASE_URI
          valueFrom:
            secretKeyRef:
              name: commonurl-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: FDK_BASE_URI
        image: {{ required "Missing value DOCKER_IMAGE_NAME" .Values.DOCKER_IMAGE_NAME }}
        imagePullPolicy: Always
        name: dcat-ap-no-validator-gui
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: {{ required "Missing value DCAT_AP_NO_VALIDATOR_GUI_MEMORY" .Values.DCAT_AP_NO_VALIDATOR_GUI_MEMORY | quote }}
      restartPolicy: Always
