{{- range .Values.kinds }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fdk-{{ .kind }}-diff-store
  namespace: {{ required "Missing value NAMESPACE" $.Values.NAMESPACE }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
{{- end }}
