---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fdk-rdf-diff-store
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 4Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fdk-rdf-diff-store
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
