#DValues for production environment
NAMESPACE: prod
STATIC_RDF_SERVER_VOLUMENAME: fdk-prod-static-rdf-server
STATIC_RDF_SERVER_STORAGESIZE: 9G
GCE_ZONE: europe-north1-a
CORS_ORIGIN_PATTERNS: https://fellesdatakatalog.digdir.no,https://*.fellesdatakatalog.digdir.no,https://data.norge.no,https://data.transportportal.no,https://transportportal.no
