#DValues for staging environment
NAMESPACE: staging
STATIC_RDF_SERVER_VOLUMENAME: fdk-dev-staging-static-rdf-server
STATIC_RDF_SERVER_STORAGESIZE: 9G
CORS_ORIGIN_PATTERNS: https://staging.fellesdatakatalog.digdir.no,https://*.staging.fellesdatakatalog.digdir.no,http://localhost:*
