kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  creationTimestamp: null
  labels:
    fdk.service: dataservice-publisher-triplestore-claim0
  name: dataservice-publisher-triplestore-claim0
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
        storageClassName: ""
        volumeName: {{ required "Missing value DATASERVICE_PUBLISHER_TRIPLESTORE_VOLUMENAME" .Values.DATASERVICE_PUBLISHER_TRIPLESTORE_VOLUMENAME }}
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ required "Missing value DATASERVICE_PUBLISHER_TRIPLESTORE_STORAGESIZE" .Values.DATASERVICE_PUBLISHER_TRIPLESTORE_STORAGESIZE }}
status: {}
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ required "Missing value DATASERVICE_PUBLISHER_TRIPLESTORE_VOLUMENAME" .Values.DATASERVICE_PUBLISHER_TRIPLESTORE_VOLUMENAME }}
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  storageClassName: ""
  capacity:
    storage: {{ required "Missing value DATASERVICE_PUBLISHER_TRIPLESTORE_STORAGESIZE" .Values.DATASERVICE_PUBLISHER_TRIPLESTORE_STORAGESIZE }}
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: {{ required "Missing value DATASERVICE_PUBLISHER_TRIPLESTORE_VOLUMENAME" .Values.DATASERVICE_PUBLISHER_TRIPLESTORE_VOLUMENAME }}
    fsType: ext4
