apiVersion: v1
appVersion: "1.0"
description: FDK Informationmodel Harvester
name: fdk-informationmodel-harvester
version: 0.1.0
home: https://github.com/Informasjonsforvaltning/fdk-informationmodel-harvester