apiVersion: v1
appVersion: "1.0"
description: This service listens to dataset harvested events (Kafka) and checks if the dataset has defined/set specific properties.
name: fdk-mqa-property-checker
version: 0.1.0
home: https://github.com/Informasjonsforvaltning/fdk-mqa-property-checker