kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    fdk.service: catalog-store-claim0
  name: catalog-store-claim0
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  storageClassName: ""
  volumeName: {{ required "Missing value CATALOG_STORE_VOLUMENAME" .Values.CATALOG_STORE_VOLUMENAME }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ required "Missing value CATALOG_STORE_STORAGESIZE" .Values.CATALOG_STORE_STORAGESIZE }}

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ required "Missing value CATALOG_STORE_VOLUMENAME" .Values.CATALOG_STORE_VOLUMENAME }}
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  storageClassName: ""
  capacity:
    storage: {{ required "Missing value CATALOG_STORE_STORAGESIZE" .Values.CATALOG_STORE_STORAGESIZE }}
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: {{ required "Missing value CATALOG_STORE_VOLUMENAME" .Values.CATALOG_STORE_VOLUMENAME }}
    fsType: ext4
