---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    fdk.service: rdf-prettifier
  name: rdf-prettifier
  namespace: {{ required "Missing value NAMESPACE" $.Values.NAMESPACE }}
spec:
  replicas: 1
  selector:
    matchLabels:
      fdk.service: rdf-prettifier
  template:
    metadata:
      labels:
        fdk.service: rdf-prettifier
    spec:
      containers:
        - name: rdf-prettifier
          image: {{ required "Missing value DOCKER_IMAGE_NAME" $.Values.DOCKER_IMAGE_NAME }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: rdf-prettifier
                  key: API_KEY
          resources:
            requests:
              cpu: {{ required "Missing value RDF_PRETTIFIER_CPU" $.Values.RDF_PRETTIFIER_CPU | quote }}
              memory: {{ required "Missing value RDF_PRETTIFIER_MEMORY" $.Values.RDF_PRETTIFIER_MEMORY | quote }}
            limits:
                memory: {{ required "Missing value RDF_PRETTIFIER_MEMORY" $.Values.RDF_PRETTIFIER_MEMORY | quote }}
          livenessProbe:
            httpGet:
              path: /livez
              port: 80
          readinessProbe:
            httpGet:
              path: /readyz
              port: 80
      restartPolicy: Always
