apiVersion: v1
appVersion: "1.0"
description: Backend-for-frontend service that provides content for fdk portal's metadata quality pages.
name: fdk-metadata-quality-bff
version: 0.1.0
home: https://github.com/Informasjonsforvaltning/fdk-metadata-quality-bff