apiVersion: v1
appVersion: "1.0"
description: Template service for records of processing activities gui.
name: records-of-processing-activities-gui
version: 0.1.0
home: https://github.com/Informasjonsforvaltning/records-of-processing-activities-gui